### ISSUE TITLE
Filtering snippets by author doesn't work

### ISSUE THREAD

**Issue by Nerakc** [mozkomor05/wpd-code-snippets#5]
## Describe the bug
Searching by author in browse menu causes fatal error.

## To Reproduce
1. Go to "browse" menu
2. Select search by "Author"
3. Write name of any author
4. Press enter

## Expected behavior
Plugin should show me list of snippets created by selected author.

## Setup
 - PHP version: 8.0.9
 - WP version: 5.8.1
 - OS: Windows 10

**Comment by mozkomor05** [comment]
**The error:**

    Fatal error: Uncaught TypeError: Unsupported operand types: string / int in /srv/http/wp-admin/includes/class-wp-list-table.php:287 Stack trace: #0 /srv/http/wp-content/plugins/wpd-code-snippets/php/class-list-table-browse.php(124): WP_List_Table->set_pagination_args() #1 /srv/http/wp-content/plugins/wpd-code-snippets/php/admin-menus/class-browse-menu.php(44): Code_Snippets_List_Table_Browse->prepare_items() #2 /srv/http/wp-includes/class-wp-hook.php(303): Code_Snippets_Browse_Menu->load() #3 /srv/http/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #4 /srv/http/wp-includes/plugin.php(470): WP_Hook->do_action() #5 /srv/http/wp-admin/admin.php(237): do_action() #6 {main} thrown in /srv/http/wp-admin/includes/class-wp-list-table.php on line 287
